### PR TITLE
2.x: Fix license, remove static lib, update to 2.9.9

### PR DESCRIPTION
**Pull request by mbargull**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mbargull** [comment]
@xmnlab, could you review this? It is a followup to gh-7.

**Review by xmnlab — APPROVED** [review]
LGTM! thanks @mbargull !

**Comment by xmnlab** [comment]
@asafkahlon could you review this PR? (note: I don't have write permissions here)

**Comment by mbargull** [comment]
Thanks all!

> (note: I don't have write permissions here)

Fixing that with gh-9 ;).

**Pull request merged**
